# Generated by Django 5.0.4 on 2024-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0004_service_alter_costumer_image_alter_foodmenu_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableonline',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
