# Generated by Django 5.0.4 on 2024-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0005_alter_tableonline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableonline',
            name='name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
