# Generated by Django 5.0.4 on 2024-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0007_rename_name_tableonline_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableonline',
            name='date_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
