# Generated by Django 5.0.4 on 2024-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0008_alter_tableonline_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableonline',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
